module.exports = {
    PORT: process.env.PORT || 5000,
    MONGO_URL: process.env.MONGO_URL || 'mongodb://localhost:27017/test',

    ACCESS_SECRET_WORD: process.env.ACCESS_SECRET_WORD,
    REFRESH_SECRET_WORD: process.env.REFRESH_SECRET_WORD,

    ACCESS_SECRET_WORD_USER: process.env.ACCESS_SECRET_WORD_USER,
    REFRESH_SECRET_WORD_USER: process.env.REFRESH_SECRET_WORD_USER,

    ACCESS_SECRET_WORD_COMPANY: process.env.ACCESS_SECRET_WORD_COMPANY,
    REFRESH_SECRET_WORD_COMPANY: process.env.REFRESH_SECRET_WORD_COMPANY,

    ACCESS_SECRET_WORD_ADMIN: process.env.ACCESS_SECRET_WORD_ADMIN,
    REFRESH_SECRET_WORD_ADMIN: process.env.REFRESH_SECRET_WORD_ADMIN,

    // FORGOT_PASSWORD_USER_WORD: process.env.FORGOT_PASSWORD_USER_WORD,
    ORDER_CAR_WORD: process.env.ORDER_CAR_WORD,

    NO_REPLY_EMAIL: process.env.NO_REPLY_EMAIL || 'alinatyndyk777@gmail.com',
    NO_REPLY_PASSWORD: process.env.NO_REPLY_PASSWORD || 'evutrdewpnrsuqqh',

    FRONTEND_URL: process.env.FRONTEND_URL || 'google.com',
    ACTION_TOKEN_SECRET: process.env.ACTION_TOKEN_WORD || 'ACTION_TOKEN'
}